export type FlashReportCountryDataset = {
  slug: string;
  name: string;
  modules: string[];
};

export const FLASH_REPORT_COUNTRY_DATASETS: Record<
  string,
  FlashReportCountryDataset
> = {
  india: {
    slug: "india",
    name: "India",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "Alternative Fuel Adoption Segment-wise Comparison",
      "2W Sales Forecast",
      "2W OEM Segment Share",
      "2W EV Electric OEM Market Share",
      "2W Application Chart",
      "3W Sales Forecast",
      "3W OEM Segment Share",
      "3W EV Electric OEM Market Share",
      "3W Application Chart",
      "CV Sales Forecast",
      "CV Segment Split",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Truck Application Chart",
      "Truck Segment Contribution",
      "Bus Sales Forecast",
      "Bus OEM Segment Share",
      "Buses Segment Contribution",
      "Buses Application Chart",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "Passenger Vehicle EV Electric OEM Market Share",
      "Passenger Vehicle Application Chart",
      "AG Tractor Sales Forecast",
      "AG Tractor OEM Segment Share",
      "AG Tractor Application Chart",
      "Construction Equipment Sales Forecast",
      "Construction Equipment OEM Segment Share",
    ],
  },
  brazil: {
    slug: "brazil",
    name: "Brazil",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W Application Chart",
      "2W OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck Application Chart",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
      "Buses Application Chart",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "Passenger Vehicle Application Chart",
      "AG Tractor Sales Forecast",
      "AG Tractor Application Chart",
    ],
  },
  "south-africa": {
    slug: "south-africa",
    name: "South Africa",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
      "AG Tractor Sales Forecast",
    ],
  },
  japan: {
    slug: "japan",
    name: "Japan",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle EV Electric OEM Market Share",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
    ],
  },
  sweden: {
    slug: "sweden",
    name: "Sweden",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W Application Chart",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "Passenger Vehicle EV Electric OEM Market Share",
      "Passenger Vehicle Application Chart",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Truck Application Chart",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
      "Bus Application Chart",
      "AG Tractor Sales Forecast",
      "AG Application Chart",
    ],
  },
  vietnam: {
    slug: "vietnam",
    name: "Vietnam",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
    ],
  },
  chile: {
    slug: "chile",
    name: "Chile",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
    ],
  },
  pakistan: {
    slug: "pakistan",
    name: "Pakistan",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W OEM Segment Share",
      "3W Sales Forecast",
      "3W OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "AG Tractor Sales Forecast",
      "AG Tractor OEM Segment Share",
    ],
  },
  colombia: {
    slug: "colombia",
    name: "Colombia",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W OEM Segment Share",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
    ],
  },
  australia: {
    slug: "australia",
    name: "Australia",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
    ],
  },
  germany: {
    slug: "germany",
    name: "Germany",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W OEM Segment Share",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
      "AG Tractor Sales Forecast",
      "AG Tractor OEM Segment Share",
    ],
  },
  peru: {
    slug: "peru",
    name: "Peru",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W OEM Segment Share",
      "3W Sales Forecast",
      "3W OEM Segment Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
    ],
  },
  russia: {
    slug: "russia",
    name: "Russia",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W OEM Segment Share",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "Passenger Vehicle EV Electric OEM Market Share",
      "CV Sales Forecast",
      "CV OEM Segment Share",
      "Truck Sales Forecast",
      "Truck OEM Segment Share",
      "Buses Sales Forecast",
      "Bus OEM Segment Share",
    ],
  },
  belgium: {
    slug: "belgium",
    name: "Belgium",
    modules: [
      "Overall Automotive Industry Sales Forecast",
      "2W Sales Forecast",
      "2W OEM Segment Share",
      "Passenger Vehicle Sales Forecast",
      "Passenger Vehicle OEM Segment Share",
      "CV Sales Forecast",
      "Truck Sales Forecast",
      "Buses Sales Forecast",
      "AG Tractor Sales Forecast",
    ],
  },
};

export function getFlashReportCountryDataset(country: string) {
  const key = String(country || "").trim().toLowerCase();
  return FLASH_REPORT_COUNTRY_DATASETS[key] || null;
}

