// AUTO-GENERATED — do not edit by hand. Regenerate with scripts/gen-world-countries.js
// (requires: npm i world-countries --no-save). Complete ISO 3166-1 country ->
// { name, iso2, region } so ANY country in the hierarchy resolves a flag + region,
// not just the launch markets. Region keys match FlashRegionKey in flashReportRegistry.
import type { FlashRegionKey } from "@/lib/flashReportRegistry";

export type WorldCountry = { name: string; iso2: string; region: FlashRegionKey };

// Keyed by normalized country name/alias (matches the countries API normKey).
export const WORLD_COUNTRIES: Record<string, WorldCountry> = {
  "a-ml": { name: "Somalia", iso2: "SO", region: "middle-east-africa" },
  "aaland": { name: "Åland Islands", iso2: "AX", region: "europe" },
  "afghanistan": { name: "Afghanistan", iso2: "AF", region: "asia-pacific" },
  "afnistn": { name: "Afghanistan", iso2: "AF", region: "asia-pacific" },
  "ahvenanmaa": { name: "Åland Islands", iso2: "AX", region: "europe" },
  "al-ittid-al-qumur": { name: "Comoros", iso2: "KM", region: "middle-east-africa" },
  "al-jumhriyyah-al-islmiyyah-al-mrtniyyah": { name: "Mauritania", iso2: "MR", region: "middle-east-africa" },
  "al-jumhriyyah-al-yamaniyyah": { name: "Yemen", iso2: "YE", region: "middle-east-africa" },
  "al-jumhriyyah-at-tnisiyyah": { name: "Tunisia", iso2: "TN", region: "middle-east-africa" },
  "al-jumhryah-al-arabyah-as-sryah": { name: "Syria", iso2: "SY", region: "middle-east-africa" },
  "al-jumhryah-al-libnnyah": { name: "Lebanon", iso2: "LB", region: "middle-east-africa" },
  "al-mamlakah-al-arabiyyah-as-sudiyyah": { name: "Saudi Arabia", iso2: "SA", region: "middle-east-africa" },
  "al-mamlakah-al-maribiyah": { name: "Morocco", iso2: "MA", region: "middle-east-africa" },
  "al-mamlakah-al-urdunyah-al-hshimyah": { name: "Jordan", iso2: "JO", region: "middle-east-africa" },
  "aland": { name: "Åland Islands", iso2: "AX", region: "europe" },
  "albania": { name: "Albania", iso2: "AL", region: "europe" },
  "algeria": { name: "Algeria", iso2: "DZ", region: "middle-east-africa" },
  "algrie": { name: "Algeria", iso2: "DZ", region: "middle-east-africa" },
  "amelika-smoa": { name: "American Samoa", iso2: "AS", region: "asia-pacific" },
  "american-samoa": { name: "American Samoa", iso2: "AS", region: "asia-pacific" },
  "amerika-smoa": { name: "American Samoa", iso2: "AS", region: "asia-pacific" },
  "andorra": { name: "Andorra", iso2: "AD", region: "europe" },
  "angola": { name: "Angola", iso2: "AO", region: "middle-east-africa" },
  "anguilla": { name: "Anguilla", iso2: "AI", region: "latin-america" },
  "antarctica": { name: "Antarctica", iso2: "AQ", region: "asia-pacific" },
  "antigua-and-barbuda": { name: "Antigua and Barbuda", iso2: "AG", region: "latin-america" },
  "aolepn-aorkin-maje": { name: "Marshall Islands", iso2: "MH", region: "asia-pacific" },
  "aotearoa": { name: "New Zealand", iso2: "NZ", region: "asia-pacific" },
  "arab-republic-of-egypt": { name: "Egypt", iso2: "EG", region: "middle-east-africa" },
  "argentina": { name: "Argentina", iso2: "AR", region: "latin-america" },
  "argentine-republic": { name: "Argentina", iso2: "AR", region: "latin-america" },
  "armenia": { name: "Armenia", iso2: "AM", region: "middle-east-africa" },
  "aruba": { name: "Aruba", iso2: "AW", region: "latin-america" },
  "australia": { name: "Australia", iso2: "AU", region: "asia-pacific" },
  "austria": { name: "Austria", iso2: "AT", region: "europe" },
  "azerbaijan": { name: "Azerbaijan", iso2: "AZ", region: "middle-east-africa" },
  "azrbaycan-respublikas": { name: "Azerbaijan", iso2: "AZ", region: "middle-east-africa" },
  "bahamas": { name: "Bahamas", iso2: "BS", region: "latin-america" },
  "bahrain": { name: "Bahrain", iso2: "BH", region: "middle-east-africa" },
  "bailiwick-of-guernsey": { name: "Guernsey", iso2: "GG", region: "europe" },
  "bailiwick-of-jersey": { name: "Jersey", iso2: "JE", region: "europe" },
  "bailliage-d-jrri": { name: "Jersey", iso2: "JE", region: "europe" },
  "bailliage-de-guernesey": { name: "Guernsey", iso2: "GG", region: "europe" },
  "bailliage-de-jersey": { name: "Jersey", iso2: "JE", region: "europe" },
  "bangladesh": { name: "Bangladesh", iso2: "BD", region: "asia-pacific" },
  "barbados": { name: "Barbados", iso2: "BB", region: "latin-america" },
  "belarus": { name: "Belarus", iso2: "BY", region: "europe" },
  "belgi": { name: "Belgium", iso2: "BE", region: "europe" },
  "belgie": { name: "Belgium", iso2: "BE", region: "europe" },
  "belgien": { name: "Belgium", iso2: "BE", region: "europe" },
  "belgique": { name: "Belgium", iso2: "BE", region: "europe" },
  "belgium": { name: "Belgium", iso2: "BE", region: "europe" },
  "belize": { name: "Belize", iso2: "BZ", region: "latin-america" },
  "beluu-er-a-belau": { name: "Palau", iso2: "PW", region: "asia-pacific" },
  "benin": { name: "Benin", iso2: "BJ", region: "middle-east-africa" },
  "bermuda": { name: "Bermuda", iso2: "BM", region: "north-america" },
  "bes-islands": { name: "Caribbean Netherlands", iso2: "BQ", region: "latin-america" },
  "bharat-ganrajya": { name: "India", iso2: "IN", region: "asia-pacific" },
  "bhrat": { name: "India", iso2: "IN", region: "asia-pacific" },
  "bhutan": { name: "Bhutan", iso2: "BT", region: "asia-pacific" },
  "bielaru": { name: "Belarus", iso2: "BY", region: "europe" },
  "bolivarian-republic-of-venezuela": { name: "Venezuela", iso2: "VE", region: "latin-america" },
  "bolivia": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "bolivia-plurinational-state-of": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "bonaire-sint-eustatius-and-saba": { name: "Caribbean Netherlands", iso2: "BQ", region: "latin-america" },
  "bosnia-and-herzegovina": { name: "Bosnia and Herzegovina", iso2: "BA", region: "europe" },
  "bosnia-herzegovina": { name: "Bosnia and Herzegovina", iso2: "BA", region: "europe" },
  "botswana": { name: "Botswana", iso2: "BW", region: "middle-east-africa" },
  "bouvet-island": { name: "Bouvet Island", iso2: "BV", region: "asia-pacific" },
  "bouvet-ya": { name: "Bouvet Island", iso2: "BV", region: "asia-pacific" },
  "bouvetya": { name: "Bouvet Island", iso2: "BV", region: "asia-pacific" },
  "brasil": { name: "Brazil", iso2: "BR", region: "latin-america" },
  "brazil": { name: "Brazil", iso2: "BR", region: "latin-america" },
  "britain": { name: "United Kingdom", iso2: "GB", region: "europe" },
  "british-indian-ocean-territory": { name: "British Indian Ocean Territory", iso2: "IO", region: "middle-east-africa" },
  "british-virgin-islands": { name: "British Virgin Islands", iso2: "VG", region: "latin-america" },
  "brunei": { name: "Brunei", iso2: "BN", region: "asia-pacific" },
  "brunei-darussalam": { name: "Brunei", iso2: "BN", region: "asia-pacific" },
  "bulgaria": { name: "Bulgaria", iso2: "BG", region: "europe" },
  "buliwya": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "buliwya-mamallaqta": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "bundesrepublik-deutschland": { name: "Germany", iso2: "DE", region: "europe" },
  "burkina-faso": { name: "Burkina Faso", iso2: "BF", region: "middle-east-africa" },
  "burma": { name: "Myanmar", iso2: "MM", region: "asia-pacific" },
  "burundi": { name: "Burundi", iso2: "BI", region: "middle-east-africa" },
  "cambodia": { name: "Cambodia", iso2: "KH", region: "asia-pacific" },
  "cameroon": { name: "Cameroon", iso2: "CM", region: "middle-east-africa" },
  "canada": { name: "Canada", iso2: "CA", region: "north-america" },
  "cape-verde": { name: "Cape Verde", iso2: "CV", region: "middle-east-africa" },
  "caribbean-netherlands": { name: "Caribbean Netherlands", iso2: "BQ", region: "latin-america" },
  "cayman-islands": { name: "Cayman Islands", iso2: "KY", region: "latin-america" },
  "central-african-republic": { name: "Central African Republic", iso2: "CF", region: "middle-east-africa" },
  "chad": { name: "Chad", iso2: "TD", region: "middle-east-africa" },
  "chile": { name: "Chile", iso2: "CL", region: "latin-america" },
  "china": { name: "China", iso2: "CN", region: "asia-pacific" },
  "chinese-taipei": { name: "Taiwan", iso2: "TW", region: "asia-pacific" },
  "chosn-minjujui-inmin-konghwaguk": { name: "North Korea", iso2: "KP", region: "asia-pacific" },
  "christmas-island": { name: "Christmas Island", iso2: "CX", region: "asia-pacific" },
  "cng-ha-x-hi-ch-ngha-vit-nam": { name: "Vietnam", iso2: "VN", region: "asia-pacific" },
  "co-operative-republic-of-guyana": { name: "Guyana", iso2: "GY", region: "latin-america" },
  "cocos-islands": { name: "Cocos (Keeling) Islands", iso2: "CC", region: "asia-pacific" },
  "cocos-keeling-islands": { name: "Cocos (Keeling) Islands", iso2: "CC", region: "asia-pacific" },
  "collectivit-de-saint-barthlemy": { name: "Saint Barthélemy", iso2: "BL", region: "latin-america" },
  "collectivit-de-saint-martin": { name: "Saint Martin", iso2: "MF", region: "latin-america" },
  "collectivit-territoriale-de-saint-pierre-et-miquelon": { name: "Saint Pierre and Miquelon", iso2: "PM", region: "north-america" },
  "collectivity-of-saint-barthlemy": { name: "Saint Barthélemy", iso2: "BL", region: "latin-america" },
  "collectivity-of-saint-martin": { name: "Saint Martin", iso2: "MF", region: "latin-america" },
  "colombia": { name: "Colombia", iso2: "CO", region: "latin-america" },
  "commonwealth-of-australia": { name: "Australia", iso2: "AU", region: "asia-pacific" },
  "commonwealth-of-dominica": { name: "Dominica", iso2: "DM", region: "latin-america" },
  "commonwealth-of-puerto-rico": { name: "Puerto Rico", iso2: "PR", region: "latin-america" },
  "commonwealth-of-the-bahamas": { name: "Bahamas", iso2: "BS", region: "latin-america" },
  "commonwealth-of-the-northern-mariana-islands": { name: "Northern Mariana Islands", iso2: "MP", region: "asia-pacific" },
  "comoros": { name: "Comoros", iso2: "KM", region: "middle-east-africa" },
  "congo": { name: "Republic of the Congo", iso2: "CG", region: "middle-east-africa" },
  "congo-brazzaville": { name: "Republic of the Congo", iso2: "CG", region: "middle-east-africa" },
  "congo-kinshasa": { name: "DR Congo", iso2: "CD", region: "middle-east-africa" },
  "congo-the-democratic-republic-of-the": { name: "DR Congo", iso2: "CD", region: "middle-east-africa" },
  "cook-islands": { name: "Cook Islands", iso2: "CK", region: "asia-pacific" },
  "costa-rica": { name: "Costa Rica", iso2: "CR", region: "latin-america" },
  "cote-divoire": { name: "Ivory Coast", iso2: "CI", region: "middle-east-africa" },
  "country-of-curaao": { name: "Curaçao", iso2: "CW", region: "latin-america" },
  "crna-gora": { name: "Montenegro", iso2: "ME", region: "europe" },
  "croatia": { name: "Croatia", iso2: "HR", region: "europe" },
  "cte-divoire": { name: "Ivory Coast", iso2: "CI", region: "middle-east-africa" },
  "cuba": { name: "Cuba", iso2: "CU", region: "latin-america" },
  "curaao": { name: "Curaçao", iso2: "CW", region: "latin-america" },
  "curacao": { name: "Curaçao", iso2: "CW", region: "latin-america" },
  "cyprus": { name: "Cyprus", iso2: "CY", region: "europe" },
  "czech-republic": { name: "Czechia", iso2: "CZ", region: "europe" },
  "czechia": { name: "Czechia", iso2: "CZ", region: "europe" },
  "danmark": { name: "Denmark", iso2: "DK", region: "europe" },
  "dawlat-al-kuwait": { name: "Kuwait", iso2: "KW", region: "middle-east-africa" },
  "dawlat-filasin": { name: "Palestine", iso2: "PS", region: "middle-east-africa" },
  "dawlat-iritriy": { name: "Eritrea", iso2: "ER", region: "middle-east-africa" },
  "dawlat-libya": { name: "Libya", iso2: "LY", region: "middle-east-africa" },
  "dawlat-qaar": { name: "Qatar", iso2: "QA", region: "middle-east-africa" },
  "democratic-peoples-republic-of-korea": { name: "North Korea", iso2: "KP", region: "asia-pacific" },
  "democratic-republic-of-congo": { name: "DR Congo", iso2: "CD", region: "middle-east-africa" },
  "democratic-republic-of-so-tom-and-prncipe": { name: "São Tomé and Príncipe", iso2: "ST", region: "middle-east-africa" },
  "democratic-republic-of-the-congo": { name: "DR Congo", iso2: "CD", region: "middle-east-africa" },
  "democratic-republic-of-timor-leste": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "democratic-socialist-republic-of-sri-lanka": { name: "Sri Lanka", iso2: "LK", region: "asia-pacific" },
  "denmark": { name: "Denmark", iso2: "DK", region: "europe" },
  "department-of-mayotte": { name: "Mayotte", iso2: "YT", region: "middle-east-africa" },
  "dhivehi-raajjeyge-jumhooriyya": { name: "Maldives", iso2: "MV", region: "asia-pacific" },
  "djibouti": { name: "Djibouti", iso2: "DJ", region: "middle-east-africa" },
  "dominica": { name: "Dominica", iso2: "DM", region: "latin-america" },
  "dominican-republic": { name: "Dominican Republic", iso2: "DO", region: "latin-america" },
  "dominique": { name: "Dominica", iso2: "DM", region: "latin-america" },
  "dpartement-de-mayotte": { name: "Mayotte", iso2: "YT", region: "middle-east-africa" },
  "dprk": { name: "North Korea", iso2: "KP", region: "asia-pacific" },
  "dr-congo": { name: "DR Congo", iso2: "CD", region: "middle-east-africa" },
  "dzayer": { name: "Algeria", iso2: "DZ", region: "middle-east-africa" },
  "east-timor": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "ecuador": { name: "Ecuador", iso2: "EC", region: "latin-america" },
  "eesti": { name: "Estonia", iso2: "EE", region: "europe" },
  "eesti-vabariik": { name: "Estonia", iso2: "EE", region: "europe" },
  "egypt": { name: "Egypt", iso2: "EG", region: "middle-east-africa" },
  "el-salvador": { name: "El Salvador", iso2: "SV", region: "latin-america" },
  "ellan-vannin": { name: "Isle of Man", iso2: "IM", region: "europe" },
  "ellda": { name: "Greece", iso2: "GR", region: "europe" },
  "emirates": { name: "United Arab Emirates", iso2: "AE", region: "middle-east-africa" },
  "equatorial-guinea": { name: "Equatorial Guinea", iso2: "GQ", region: "middle-east-africa" },
  "eritrea": { name: "Eritrea", iso2: "ER", region: "middle-east-africa" },
  "ertr": { name: "Eritrea", iso2: "ER", region: "middle-east-africa" },
  "esk-republika": { name: "Czechia", iso2: "CZ", region: "europe" },
  "esko": { name: "Czechia", iso2: "CZ", region: "europe" },
  "estado-libre-asociado-de-puerto-rico": { name: "Puerto Rico", iso2: "PR", region: "latin-america" },
  "estado-plurinacional-de-bolivia": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "estados-unidos-mexicanos": { name: "Mexico", iso2: "MX", region: "latin-america" },
  "estonia": { name: "Estonia", iso2: "EE", region: "europe" },
  "eswatini": { name: "Eswatini", iso2: "SZ", region: "middle-east-africa" },
  "ethiopia": { name: "Ethiopia", iso2: "ET", region: "middle-east-africa" },
  "faeroe-islands": { name: "Faroe Islands", iso2: "FO", region: "europe" },
  "falkland-islands": { name: "Falkland Islands", iso2: "FK", region: "latin-america" },
  "falkland-islands-malvinas": { name: "Falkland Islands", iso2: "FK", region: "latin-america" },
  "faroe-islands": { name: "Faroe Islands", iso2: "FO", region: "europe" },
  "federal-democratic-republic-of-ethiopia": { name: "Ethiopia", iso2: "ET", region: "middle-east-africa" },
  "federal-democratic-republic-of-nepal": { name: "Nepal", iso2: "NP", region: "asia-pacific" },
  "federal-republic-of-germany": { name: "Germany", iso2: "DE", region: "europe" },
  "federal-republic-of-nigeria": { name: "Nigeria", iso2: "NG", region: "middle-east-africa" },
  "federal-republic-of-somalia": { name: "Somalia", iso2: "SO", region: "middle-east-africa" },
  "federated-states-of-micronesia": { name: "Micronesia", iso2: "FM", region: "asia-pacific" },
  "federation-of-saint-christopher-and-nevis": { name: "Saint Kitts and Nevis", iso2: "KN", region: "latin-america" },
  "federative-republic-of-brazil": { name: "Brazil", iso2: "BR", region: "latin-america" },
  "fij-gaarjya": { name: "Fiji", iso2: "FJ", region: "asia-pacific" },
  "fiji": { name: "Fiji", iso2: "FJ", region: "asia-pacific" },
  "finland": { name: "Finland", iso2: "FI", region: "europe" },
  "france": { name: "France", iso2: "FR", region: "europe" },
  "french-guiana": { name: "French Guiana", iso2: "GF", region: "latin-america" },
  "french-polynesia": { name: "French Polynesia", iso2: "PF", region: "asia-pacific" },
  "french-republic": { name: "France", iso2: "FR", region: "europe" },
  "french-southern-and-antarctic-lands": { name: "French Southern and Antarctic Lands", iso2: "TF", region: "asia-pacific" },
  "french-southern-territories": { name: "French Southern and Antarctic Lands", iso2: "TF", region: "asia-pacific" },
  "frerne": { name: "Faroe Islands", iso2: "FO", region: "europe" },
  "froyar": { name: "Faroe Islands", iso2: "FO", region: "europe" },
  "frstentum-liechtenstein": { name: "Liechtenstein", iso2: "LI", region: "europe" },
  "gabon": { name: "Gabon", iso2: "GA", region: "middle-east-africa" },
  "gabonese-republic": { name: "Gabon", iso2: "GA", region: "middle-east-africa" },
  "gabuuti": { name: "Djibouti", iso2: "DJ", region: "middle-east-africa" },
  "gabuutih-ummuuno": { name: "Djibouti", iso2: "DJ", region: "middle-east-africa" },
  "gambia": { name: "Gambia", iso2: "GM", region: "middle-east-africa" },
  "georgia": { name: "Georgia", iso2: "GE", region: "middle-east-africa" },
  "germany": { name: "Germany", iso2: "DE", region: "europe" },
  "ghana": { name: "Ghana", iso2: "GH", region: "middle-east-africa" },
  "gibraltar": { name: "Gibraltar", iso2: "GI", region: "europe" },
  "gnprjatntri-bangladesh": { name: "Bangladesh", iso2: "BD", region: "asia-pacific" },
  "grand-duch-de-luxembourg": { name: "Luxembourg", iso2: "LU", region: "europe" },
  "grand-duchy-of-luxembourg": { name: "Luxembourg", iso2: "LU", region: "europe" },
  "great-britain": { name: "United Kingdom", iso2: "GB", region: "europe" },
  "greece": { name: "Greece", iso2: "GR", region: "europe" },
  "greenland": { name: "Greenland", iso2: "GL", region: "north-america" },
  "grenada": { name: "Grenada", iso2: "GD", region: "latin-america" },
  "grnland": { name: "Greenland", iso2: "GL", region: "north-america" },
  "groherzogtum-luxemburg": { name: "Luxembourg", iso2: "LU", region: "europe" },
  "groussherzogtum-ltzebuerg": { name: "Luxembourg", iso2: "LU", region: "europe" },
  "guadeloupe": { name: "Guadeloupe", iso2: "GP", region: "latin-america" },
  "guam": { name: "Guam", iso2: "GU", region: "asia-pacific" },
  "guatemala": { name: "Guatemala", iso2: "GT", region: "latin-america" },
  "guernsey": { name: "Guernsey", iso2: "GG", region: "europe" },
  "guhn": { name: "Guam", iso2: "GU", region: "asia-pacific" },
  "guiana": { name: "French Guiana", iso2: "GF", region: "latin-america" },
  "guinea": { name: "Guinea", iso2: "GN", region: "middle-east-africa" },
  "guinea-bissau": { name: "Guinea-Bissau", iso2: "GW", region: "middle-east-africa" },
  "guyana": { name: "Guyana", iso2: "GY", region: "latin-america" },
  "guyane": { name: "French Guiana", iso2: "GF", region: "latin-america" },
  "gwadloup": { name: "Guadeloupe", iso2: "GP", region: "latin-america" },
  "haiti": { name: "Haiti", iso2: "HT", region: "latin-america" },
  "hashemite-kingdom-of-jordan": { name: "Jordan", iso2: "JO", region: "middle-east-africa" },
  "hayastan": { name: "Armenia", iso2: "AM", region: "middle-east-africa" },
  "heard-island-and-mcdonald-islands": { name: "Heard Island and McDonald Islands", iso2: "HM", region: "asia-pacific" },
  "hellenic-republic": { name: "Greece", iso2: "GR", region: "europe" },
  "holland": { name: "Netherlands", iso2: "NL", region: "europe" },
  "holy-see-vatican-city-state": { name: "Vatican City", iso2: "VA", region: "europe" },
  "honduras": { name: "Honduras", iso2: "HN", region: "latin-america" },
  "hong-kong": { name: "Hong Kong", iso2: "HK", region: "asia-pacific" },
  "hong-kong-special-administrative-region-of-the-peoples-republic-of-china": { name: "Hong Kong", iso2: "HK", region: "asia-pacific" },
  "hrvatska": { name: "Croatia", iso2: "HR", region: "europe" },
  "hungary": { name: "Hungary", iso2: "HU", region: "europe" },
  "iceland": { name: "Iceland", iso2: "IS", region: "europe" },
  "ilakai": { name: "Sri Lanka", iso2: "LK", region: "asia-pacific" },
  "independen-stet-bilong-papua-niugini": { name: "Papua New Guinea", iso2: "PG", region: "asia-pacific" },
  "independent-and-sovereign-republic-of-kiribati": { name: "Kiribati", iso2: "KI", region: "asia-pacific" },
  "independent-state-of-papua-new-guinea": { name: "Papua New Guinea", iso2: "PG", region: "asia-pacific" },
  "independent-state-of-samoa": { name: "Samoa", iso2: "WS", region: "asia-pacific" },
  "india": { name: "India", iso2: "IN", region: "asia-pacific" },
  "indonesia": { name: "Indonesia", iso2: "ID", region: "asia-pacific" },
  "iran": { name: "Iran", iso2: "IR", region: "asia-pacific" },
  "iran-islamic-republic-of": { name: "Iran", iso2: "IR", region: "asia-pacific" },
  "iraq": { name: "Iraq", iso2: "IQ", region: "middle-east-africa" },
  "ireland": { name: "Ireland", iso2: "IE", region: "europe" },
  "iritriy": { name: "Eritrea", iso2: "ER", region: "middle-east-africa" },
  "islamic-republic-of-afghanistan": { name: "Afghanistan", iso2: "AF", region: "asia-pacific" },
  "islamic-republic-of-iran": { name: "Iran", iso2: "IR", region: "asia-pacific" },
  "islamic-republic-of-mauritania": { name: "Mauritania", iso2: "MR", region: "middle-east-africa" },
  "islamic-republic-of-pakistan": { name: "Pakistan", iso2: "PK", region: "asia-pacific" },
  "island": { name: "Iceland", iso2: "IS", region: "europe" },
  "islas-malvinas": { name: "Falkland Islands", iso2: "FK", region: "latin-america" },
  "isle-of-man": { name: "Isle of Man", iso2: "IM", region: "europe" },
  "islm-jumhriyaeh-pkistn": { name: "Pakistan", iso2: "PK", region: "asia-pacific" },
  "israel": { name: "Israel", iso2: "IL", region: "middle-east-africa" },
  "italian-republic": { name: "Italy", iso2: "IT", region: "europe" },
  "italy": { name: "Italy", iso2: "IT", region: "europe" },
  "ivory-coast": { name: "Ivory Coast", iso2: "CI", region: "middle-east-africa" },
  "jabuuti": { name: "Djibouti", iso2: "DJ", region: "middle-east-africa" },
  "jamaica": { name: "Jamaica", iso2: "JM", region: "latin-america" },
  "jamhuri-ya-kenya": { name: "Kenya", iso2: "KE", region: "middle-east-africa" },
  "jamhuri-ya-muungano-wa-tanzania": { name: "Tanzania", iso2: "TZ", region: "middle-east-africa" },
  "jamhuri-ya-uganda": { name: "Uganda", iso2: "UG", region: "middle-east-africa" },
  "jamhuuriyadda-federaalka-soomaaliya": { name: "Somalia", iso2: "SO", region: "middle-east-africa" },
  "jamhuuriyadda-jabuuti": { name: "Djibouti", iso2: "DJ", region: "middle-east-africa" },
  "japan": { name: "Japan", iso2: "JP", region: "asia-pacific" },
  "jersey": { name: "Jersey", iso2: "JE", region: "europe" },
  "jomhuri-ye-eslmi-ye-irn": { name: "Iran", iso2: "IR", region: "asia-pacific" },
  "jordan": { name: "Jordan", iso2: "JO", region: "middle-east-africa" },
  "jumhriyyat-a-ml-al-fiderliyya": { name: "Somalia", iso2: "SO", region: "middle-east-africa" },
  "jumhriyyat-al-irq": { name: "Iraq", iso2: "IQ", region: "middle-east-africa" },
  "jumhryat-as-sdn": { name: "Sudan", iso2: "SD", region: "middle-east-africa" },
  "kazakhstan": { name: "Kazakhstan", iso2: "KZ", region: "asia-pacific" },
  "kbrs": { name: "Cyprus", iso2: "CY", region: "europe" },
  "kbrs-cumhuriyeti": { name: "Cyprus", iso2: "CY", region: "europe" },
  "keeling-islands": { name: "Cocos (Keeling) Islands", iso2: "CC", region: "asia-pacific" },
  "kenya": { name: "Kenya", iso2: "KE", region: "middle-east-africa" },
  "kingdom-of-bahrain": { name: "Bahrain", iso2: "BH", region: "middle-east-africa" },
  "kingdom-of-belgium": { name: "Belgium", iso2: "BE", region: "europe" },
  "kingdom-of-bhutan": { name: "Bhutan", iso2: "BT", region: "asia-pacific" },
  "kingdom-of-cambodia": { name: "Cambodia", iso2: "KH", region: "asia-pacific" },
  "kingdom-of-denmark": { name: "Denmark", iso2: "DK", region: "europe" },
  "kingdom-of-eswatini": { name: "Eswatini", iso2: "SZ", region: "middle-east-africa" },
  "kingdom-of-lesotho": { name: "Lesotho", iso2: "LS", region: "middle-east-africa" },
  "kingdom-of-morocco": { name: "Morocco", iso2: "MA", region: "middle-east-africa" },
  "kingdom-of-norway": { name: "Norway", iso2: "NO", region: "europe" },
  "kingdom-of-saudi-arabia": { name: "Saudi Arabia", iso2: "SA", region: "middle-east-africa" },
  "kingdom-of-spain": { name: "Spain", iso2: "ES", region: "europe" },
  "kingdom-of-sweden": { name: "Sweden", iso2: "SE", region: "europe" },
  "kingdom-of-thailand": { name: "Thailand", iso2: "TH", region: "asia-pacific" },
  "kingdom-of-the-netherlands": { name: "Netherlands", iso2: "NL", region: "europe" },
  "kingdom-of-tonga": { name: "Tonga", iso2: "TO", region: "asia-pacific" },
  "kiribati": { name: "Kiribati", iso2: "KI", region: "asia-pacific" },
  "kki-irani": { name: "Cook Islands", iso2: "CK", region: "asia-pacific" },
  "knigreich-belgien": { name: "Belgium", iso2: "BE", region: "europe" },
  "kongeriget-danmark": { name: "Denmark", iso2: "DK", region: "europe" },
  "kongeriket-noreg": { name: "Norway", iso2: "NO", region: "europe" },
  "kongeriket-norge": { name: "Norway", iso2: "NO", region: "europe" },
  "koninkrijk-belgi": { name: "Belgium", iso2: "BE", region: "europe" },
  "konungariket-sverige": { name: "Sweden", iso2: "SE", region: "europe" },
  "korea": { name: "South Korea", iso2: "KR", region: "asia-pacific" },
  "korea-democratic-peoples-republic-of": { name: "North Korea", iso2: "KP", region: "asia-pacific" },
  "korea-republic-of": { name: "South Korea", iso2: "KR", region: "asia-pacific" },
  "kosovo": { name: "Kosovo", iso2: "XK", region: "europe" },
  "kpros": { name: "Cyprus", iso2: "CY", region: "europe" },
  "krsou": { name: "Curaçao", iso2: "CW", region: "latin-america" },
  "kuwait": { name: "Kuwait", iso2: "KW", region: "middle-east-africa" },
  "kyrgyz-republic": { name: "Kyrgyzstan", iso2: "KG", region: "asia-pacific" },
  "kyrgyz-respublikasy": { name: "Kyrgyzstan", iso2: "KG", region: "asia-pacific" },
  "kyrgyzstan": { name: "Kyrgyzstan", iso2: "KG", region: "asia-pacific" },
  "land-curaao": { name: "Curaçao", iso2: "CW", region: "latin-america" },
  "land-islands": { name: "Åland Islands", iso2: "AX", region: "europe" },
  "lao-peoples-democratic-republic": { name: "Laos", iso2: "LA", region: "asia-pacific" },
  "laos": { name: "Laos", iso2: "LA", region: "asia-pacific" },
  "latvia": { name: "Latvia", iso2: "LV", region: "europe" },
  "latvijas-republika": { name: "Latvia", iso2: "LV", region: "europe" },
  "lebanese-republic": { name: "Lebanon", iso2: "LB", region: "middle-east-africa" },
  "lebanon": { name: "Lebanon", iso2: "LB", region: "middle-east-africa" },
  "lefatshe-la-botswana": { name: "Botswana", iso2: "BW", region: "middle-east-africa" },
  "lesotho": { name: "Lesotho", iso2: "LS", region: "middle-east-africa" },
  "liberia": { name: "Liberia", iso2: "LR", region: "middle-east-africa" },
  "libya": { name: "Libya", iso2: "LY", region: "middle-east-africa" },
  "liechtenstein": { name: "Liechtenstein", iso2: "LI", region: "europe" },
  "lietuvos-respublika": { name: "Lithuania", iso2: "LT", region: "europe" },
  "lithuania": { name: "Lithuania", iso2: "LT", region: "europe" },
  "loktntrik-ganatantra-nepl": { name: "Nepal", iso2: "NP", region: "asia-pacific" },
  "luxembourg": { name: "Luxembourg", iso2: "LU", region: "europe" },
  "lveldi-sland": { name: "Iceland", iso2: "IS", region: "europe" },
  "macao": { name: "Macau", iso2: "MO", region: "asia-pacific" },
  "macao-special-administrative-region-of-the-peoples-republic-of-china": { name: "Macau", iso2: "MO", region: "asia-pacific" },
  "macau": { name: "Macau", iso2: "MO", region: "asia-pacific" },
  "macedonia": { name: "North Macedonia", iso2: "MK", region: "europe" },
  "macedonia-the-former-yugoslav-republic-of": { name: "North Macedonia", iso2: "MK", region: "europe" },
  "madagascar": { name: "Madagascar", iso2: "MG", region: "middle-east-africa" },
  "malawi": { name: "Malawi", iso2: "MW", region: "middle-east-africa" },
  "malaysia": { name: "Malaysia", iso2: "MY", region: "asia-pacific" },
  "maldive-islands": { name: "Maldives", iso2: "MV", region: "asia-pacific" },
  "maldives": { name: "Maldives", iso2: "MV", region: "asia-pacific" },
  "mali": { name: "Mali", iso2: "ML", region: "middle-east-africa" },
  "malo-saoloto-tutoatasi-o-smoa": { name: "Samoa", iso2: "WS", region: "asia-pacific" },
  "malta": { name: "Malta", iso2: "MT", region: "europe" },
  "mamlakat-al-barayn": { name: "Bahrain", iso2: "BH", region: "middle-east-africa" },
  "mann": { name: "Isle of Man", iso2: "IM", region: "europe" },
  "mannin": { name: "Isle of Man", iso2: "IM", region: "europe" },
  "marshall-islands": { name: "Marshall Islands", iso2: "MH", region: "asia-pacific" },
  "martinique": { name: "Martinique", iso2: "MQ", region: "latin-america" },
  "matanitu-ko-viti": { name: "Fiji", iso2: "FJ", region: "asia-pacific" },
  "mauritania": { name: "Mauritania", iso2: "MR", region: "middle-east-africa" },
  "mauritius": { name: "Mauritius", iso2: "MU", region: "middle-east-africa" },
  "mayotte": { name: "Mayotte", iso2: "YT", region: "middle-east-africa" },
  "mednat-yisrel": { name: "Israel", iso2: "IL", region: "middle-east-africa" },
  "mexicanos": { name: "Mexico", iso2: "MX", region: "latin-america" },
  "mexico": { name: "Mexico", iso2: "MX", region: "latin-america" },
  "micronesia": { name: "Micronesia", iso2: "FM", region: "asia-pacific" },
  "micronesia-federated-states-of": { name: "Micronesia", iso2: "FM", region: "asia-pacific" },
  "moldova": { name: "Moldova", iso2: "MD", region: "europe" },
  "moldova-republic-of": { name: "Moldova", iso2: "MD", region: "europe" },
  "monaco": { name: "Monaco", iso2: "MC", region: "europe" },
  "mongolia": { name: "Mongolia", iso2: "MN", region: "asia-pacific" },
  "montenegro": { name: "Montenegro", iso2: "ME", region: "europe" },
  "montserrat": { name: "Montserrat", iso2: "MS", region: "latin-america" },
  "morocco": { name: "Morocco", iso2: "MA", region: "middle-east-africa" },
  "most-serene-republic-of-san-marino": { name: "San Marino", iso2: "SM", region: "europe" },
  "mozambique": { name: "Mozambique", iso2: "MZ", region: "middle-east-africa" },
  "muso-oa-lesotho": { name: "Lesotho", iso2: "LS", region: "middle-east-africa" },
  "myanmar": { name: "Myanmar", iso2: "MM", region: "asia-pacific" },
  "najr": { name: "Nigeria", iso2: "NG", region: "middle-east-africa" },
  "namibi": { name: "Namibia", iso2: "NA", region: "middle-east-africa" },
  "namibia": { name: "Namibia", iso2: "NA", region: "middle-east-africa" },
  "naoero": { name: "Nauru", iso2: "NR", region: "asia-pacific" },
  "nation-of-brunei": { name: "Brunei", iso2: "BN", region: "asia-pacific" },
  "nation-of-brunei-abode-of-peace": { name: "Brunei", iso2: "BN", region: "asia-pacific" },
  "nauru": { name: "Nauru", iso2: "NR", region: "asia-pacific" },
  "nederland": { name: "Netherlands", iso2: "NL", region: "europe" },
  "nepal": { name: "Nepal", iso2: "NP", region: "asia-pacific" },
  "netherlands": { name: "Netherlands", iso2: "NL", region: "europe" },
  "new-caledonia": { name: "New Caledonia", iso2: "NC", region: "asia-pacific" },
  "new-zealand": { name: "New Zealand", iso2: "NZ", region: "asia-pacific" },
  "ngwane": { name: "Eswatini", iso2: "SZ", region: "middle-east-africa" },
  "nicaragua": { name: "Nicaragua", iso2: "NI", region: "latin-america" },
  "niger": { name: "Niger", iso2: "NE", region: "middle-east-africa" },
  "nigeria": { name: "Nigeria", iso2: "NG", region: "middle-east-africa" },
  "nihon": { name: "Japan", iso2: "JP", region: "asia-pacific" },
  "nijar": { name: "Niger", iso2: "NE", region: "middle-east-africa" },
  "nijeriya": { name: "Nigeria", iso2: "NG", region: "middle-east-africa" },
  "nippon": { name: "Japan", iso2: "JP", region: "asia-pacific" },
  "niue": { name: "Niue", iso2: "NU", region: "asia-pacific" },
  "noreg": { name: "Norway", iso2: "NO", region: "europe" },
  "norfolk-island": { name: "Norfolk Island", iso2: "NF", region: "asia-pacific" },
  "norge": { name: "Norway", iso2: "NO", region: "europe" },
  "north-korea": { name: "North Korea", iso2: "KP", region: "asia-pacific" },
  "north-macedonia": { name: "North Macedonia", iso2: "MK", region: "europe" },
  "northern-mariana-islands": { name: "Northern Mariana Islands", iso2: "MP", region: "asia-pacific" },
  "norway": { name: "Norway", iso2: "NO", region: "europe" },
  "oesterreich": { name: "Austria", iso2: "AT", region: "europe" },
  "oman": { name: "Oman", iso2: "OM", region: "middle-east-africa" },
  "oriental-republic-of-uruguay": { name: "Uruguay", iso2: "UY", region: "latin-america" },
  "osterreich": { name: "Austria", iso2: "AT", region: "europe" },
  "ozbekiston-respublikasi": { name: "Uzbekistan", iso2: "UZ", region: "asia-pacific" },
  "pais-krsou": { name: "Curaçao", iso2: "CW", region: "latin-america" },
  "pakistan": { name: "Pakistan", iso2: "PK", region: "asia-pacific" },
  "palau": { name: "Palau", iso2: "PW", region: "asia-pacific" },
  "palestine": { name: "Palestine", iso2: "PS", region: "middle-east-africa" },
  "palestine-state-of": { name: "Palestine", iso2: "PS", region: "middle-east-africa" },
  "panama": { name: "Panama", iso2: "PA", region: "latin-america" },
  "papua-new-guinea": { name: "Papua New Guinea", iso2: "PG", region: "asia-pacific" },
  "paraguay": { name: "Paraguay", iso2: "PY", region: "latin-america" },
  "peoples-democratic-republic-of-algeria": { name: "Algeria", iso2: "DZ", region: "middle-east-africa" },
  "peoples-republic-of-bangladesh": { name: "Bangladesh", iso2: "BD", region: "asia-pacific" },
  "peoples-republic-of-china": { name: "China", iso2: "CN", region: "asia-pacific" },
  "peru": { name: "Peru", iso2: "PE", region: "latin-america" },
  "philippines": { name: "Philippines", iso2: "PH", region: "asia-pacific" },
  "pitcairn": { name: "Pitcairn Islands", iso2: "PN", region: "asia-pacific" },
  "pitcairn-group-of-islands": { name: "Pitcairn Islands", iso2: "PN", region: "asia-pacific" },
  "pitcairn-henderson-ducie-and-oeno-islands": { name: "Pitcairn Islands", iso2: "PN", region: "asia-pacific" },
  "pitcairn-islands": { name: "Pitcairn Islands", iso2: "PN", region: "asia-pacific" },
  "pkistn": { name: "Pakistan", iso2: "PK", region: "asia-pacific" },
  "pleasant-island": { name: "Nauru", iso2: "NR", region: "asia-pacific" },
  "plurinational-state-of-bolivia": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "poblacht-na-hireann": { name: "Ireland", iso2: "IE", region: "europe" },
  "poland": { name: "Poland", iso2: "PL", region: "europe" },
  "polynsie-franaise": { name: "French Polynesia", iso2: "PF", region: "asia-pacific" },
  "portugal": { name: "Portugal", iso2: "PT", region: "europe" },
  "portuguesa": { name: "Portugal", iso2: "PT", region: "europe" },
  "portuguese-republic": { name: "Portugal", iso2: "PT", region: "europe" },
  "prathet": { name: "Thailand", iso2: "TH", region: "asia-pacific" },
  "principality-of-andorra": { name: "Andorra", iso2: "AD", region: "europe" },
  "principality-of-liechtenstein": { name: "Liechtenstein", iso2: "LI", region: "europe" },
  "principality-of-monaco": { name: "Monaco", iso2: "MC", region: "europe" },
  "principat-dandorra": { name: "Andorra", iso2: "AD", region: "europe" },
  "principaut-de-monaco": { name: "Monaco", iso2: "MC", region: "europe" },
  "prnetia-farni": { name: "French Polynesia", iso2: "PF", region: "asia-pacific" },
  "publika-de-anla": { name: "Angola", iso2: "AO", region: "middle-east-africa" },
  "puerto-rico": { name: "Puerto Rico", iso2: "PR", region: "latin-america" },
  "pyidaunzu-thanmda-myma-nainngandaw": { name: "Myanmar", iso2: "MM", region: "asia-pacific" },
  "qatar": { name: "Qatar", iso2: "QA", region: "middle-east-africa" },
  "qazaqstan": { name: "Kazakhstan", iso2: "KZ", region: "asia-pacific" },
  "qazaqstan-respublkas": { name: "Kazakhstan", iso2: "KZ", region: "asia-pacific" },
  "ratcha-anachak-thai": { name: "Thailand", iso2: "TH", region: "asia-pacific" },
  "regio-administrativa-especial-de-macau-da-repblica-popular-da-china": { name: "Macau", iso2: "MO", region: "asia-pacific" },
  "reino-de-espaa": { name: "Spain", iso2: "ES", region: "europe" },
  "repblica-argentina": { name: "Argentina", iso2: "AR", region: "latin-america" },
  "repblica-bolivariana-de-venezuela": { name: "Venezuela", iso2: "VE", region: "latin-america" },
  "repblica-da-guin-bissau": { name: "Guinea-Bissau", iso2: "GW", region: "middle-east-africa" },
  "repblica-da-guin-equatorial": { name: "Equatorial Guinea", iso2: "GQ", region: "middle-east-africa" },
  "repblica-de-angola": { name: "Angola", iso2: "AO", region: "middle-east-africa" },
  "repblica-de-cabo-verde": { name: "Cape Verde", iso2: "CV", region: "middle-east-africa" },
  "repblica-de-chile": { name: "Chile", iso2: "CL", region: "latin-america" },
  "repblica-de-colombia": { name: "Colombia", iso2: "CO", region: "latin-america" },
  "repblica-de-costa-rica": { name: "Costa Rica", iso2: "CR", region: "latin-america" },
  "repblica-de-cuba": { name: "Cuba", iso2: "CU", region: "latin-america" },
  "repblica-de-el-salvador": { name: "El Salvador", iso2: "SV", region: "latin-america" },
  "repblica-de-guinea-ecuatorial": { name: "Equatorial Guinea", iso2: "GQ", region: "middle-east-africa" },
  "repblica-de-honduras": { name: "Honduras", iso2: "HN", region: "latin-america" },
  "repblica-de-moambique": { name: "Mozambique", iso2: "MZ", region: "middle-east-africa" },
  "repblica-de-nicaragua": { name: "Nicaragua", iso2: "NI", region: "latin-america" },
  "repblica-de-panam": { name: "Panama", iso2: "PA", region: "latin-america" },
  "repblica-del-ecuador": { name: "Ecuador", iso2: "EC", region: "latin-america" },
  "repblica-del-paraguay": { name: "Paraguay", iso2: "PY", region: "latin-america" },
  "repblica-del-per": { name: "Peru", iso2: "PE", region: "latin-america" },
  "repblica-democrtica-de-so-tom-e-prncipe": { name: "São Tomé and Príncipe", iso2: "ST", region: "middle-east-africa" },
  "repblica-democrtica-de-timor-leste": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "repblica-federativa-do-brasil": { name: "Brazil", iso2: "BR", region: "latin-america" },
  "repblica-oriental-del-uruguay": { name: "Uruguay", iso2: "UY", region: "latin-america" },
  "repblica-portuguesa": { name: "Portugal", iso2: "PT", region: "europe" },
  "repblika-demokrtika-timr-leste": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "repblika-ng-pilipinas": { name: "Philippines", iso2: "PH", region: "asia-pacific" },
  "repiblik-ayiti": { name: "Haiti", iso2: "HT", region: "latin-america" },
  "repiblik-sesel": { name: "Seychelles", iso2: "SC", region: "middle-east-africa" },
  "repoblikani-madagasikara": { name: "Madagascar", iso2: "MG", region: "middle-east-africa" },
  "repubblica-di-san-marino": { name: "San Marino", iso2: "SM", region: "europe" },
  "repubblica-italiana": { name: "Italy", iso2: "IT", region: "europe" },
  "repubblika-ta-malta": { name: "Malta", iso2: "MT", region: "europe" },
  "republic-of-albania": { name: "Albania", iso2: "AL", region: "europe" },
  "republic-of-angola": { name: "Angola", iso2: "AO", region: "middle-east-africa" },
  "republic-of-armenia": { name: "Armenia", iso2: "AM", region: "middle-east-africa" },
  "republic-of-austria": { name: "Austria", iso2: "AT", region: "europe" },
  "republic-of-azerbaijan": { name: "Azerbaijan", iso2: "AZ", region: "middle-east-africa" },
  "republic-of-belarus": { name: "Belarus", iso2: "BY", region: "europe" },
  "republic-of-benin": { name: "Benin", iso2: "BJ", region: "middle-east-africa" },
  "republic-of-botswana": { name: "Botswana", iso2: "BW", region: "middle-east-africa" },
  "republic-of-bulgaria": { name: "Bulgaria", iso2: "BG", region: "europe" },
  "republic-of-burundi": { name: "Burundi", iso2: "BI", region: "middle-east-africa" },
  "republic-of-cabo-verde": { name: "Cape Verde", iso2: "CV", region: "middle-east-africa" },
  "republic-of-cameroon": { name: "Cameroon", iso2: "CM", region: "middle-east-africa" },
  "republic-of-chad": { name: "Chad", iso2: "TD", region: "middle-east-africa" },
  "republic-of-chile": { name: "Chile", iso2: "CL", region: "latin-america" },
  "republic-of-china": { name: "Taiwan", iso2: "TW", region: "asia-pacific" },
  "republic-of-china-taiwan": { name: "Taiwan", iso2: "TW", region: "asia-pacific" },
  "republic-of-colombia": { name: "Colombia", iso2: "CO", region: "latin-america" },
  "republic-of-costa-rica": { name: "Costa Rica", iso2: "CR", region: "latin-america" },
  "republic-of-croatia": { name: "Croatia", iso2: "HR", region: "europe" },
  "republic-of-cte-divoire": { name: "Ivory Coast", iso2: "CI", region: "middle-east-africa" },
  "republic-of-cuba": { name: "Cuba", iso2: "CU", region: "latin-america" },
  "republic-of-cyprus": { name: "Cyprus", iso2: "CY", region: "europe" },
  "republic-of-djibouti": { name: "Djibouti", iso2: "DJ", region: "middle-east-africa" },
  "republic-of-ecuador": { name: "Ecuador", iso2: "EC", region: "latin-america" },
  "republic-of-el-salvador": { name: "El Salvador", iso2: "SV", region: "latin-america" },
  "republic-of-equatorial-guinea": { name: "Equatorial Guinea", iso2: "GQ", region: "middle-east-africa" },
  "republic-of-estonia": { name: "Estonia", iso2: "EE", region: "europe" },
  "republic-of-fiji": { name: "Fiji", iso2: "FJ", region: "asia-pacific" },
  "republic-of-finland": { name: "Finland", iso2: "FI", region: "europe" },
  "republic-of-ghana": { name: "Ghana", iso2: "GH", region: "middle-east-africa" },
  "republic-of-guatemala": { name: "Guatemala", iso2: "GT", region: "latin-america" },
  "republic-of-guinea": { name: "Guinea", iso2: "GN", region: "middle-east-africa" },
  "republic-of-guinea-bissau": { name: "Guinea-Bissau", iso2: "GW", region: "middle-east-africa" },
  "republic-of-haiti": { name: "Haiti", iso2: "HT", region: "latin-america" },
  "republic-of-honduras": { name: "Honduras", iso2: "HN", region: "latin-america" },
  "republic-of-iceland": { name: "Iceland", iso2: "IS", region: "europe" },
  "republic-of-india": { name: "India", iso2: "IN", region: "asia-pacific" },
  "republic-of-indonesia": { name: "Indonesia", iso2: "ID", region: "asia-pacific" },
  "republic-of-iraq": { name: "Iraq", iso2: "IQ", region: "middle-east-africa" },
  "republic-of-ireland": { name: "Ireland", iso2: "IE", region: "europe" },
  "republic-of-kazakhstan": { name: "Kazakhstan", iso2: "KZ", region: "asia-pacific" },
  "republic-of-kenya": { name: "Kenya", iso2: "KE", region: "middle-east-africa" },
  "republic-of-kiribati": { name: "Kiribati", iso2: "KI", region: "asia-pacific" },
  "republic-of-korea": { name: "South Korea", iso2: "KR", region: "asia-pacific" },
  "republic-of-kosovo": { name: "Kosovo", iso2: "XK", region: "europe" },
  "republic-of-latvia": { name: "Latvia", iso2: "LV", region: "europe" },
  "republic-of-liberia": { name: "Liberia", iso2: "LR", region: "middle-east-africa" },
  "republic-of-lithuania": { name: "Lithuania", iso2: "LT", region: "europe" },
  "republic-of-madagascar": { name: "Madagascar", iso2: "MG", region: "middle-east-africa" },
  "republic-of-malawi": { name: "Malawi", iso2: "MW", region: "middle-east-africa" },
  "republic-of-mali": { name: "Mali", iso2: "ML", region: "middle-east-africa" },
  "republic-of-malta": { name: "Malta", iso2: "MT", region: "europe" },
  "republic-of-mauritius": { name: "Mauritius", iso2: "MU", region: "middle-east-africa" },
  "republic-of-moldova": { name: "Moldova", iso2: "MD", region: "europe" },
  "republic-of-mozambique": { name: "Mozambique", iso2: "MZ", region: "middle-east-africa" },
  "republic-of-namibia": { name: "Namibia", iso2: "NA", region: "middle-east-africa" },
  "republic-of-nauru": { name: "Nauru", iso2: "NR", region: "asia-pacific" },
  "republic-of-nicaragua": { name: "Nicaragua", iso2: "NI", region: "latin-america" },
  "republic-of-niger": { name: "Niger", iso2: "NE", region: "middle-east-africa" },
  "republic-of-north-macedonia": { name: "North Macedonia", iso2: "MK", region: "europe" },
  "republic-of-palau": { name: "Palau", iso2: "PW", region: "asia-pacific" },
  "republic-of-panama": { name: "Panama", iso2: "PA", region: "latin-america" },
  "republic-of-paraguay": { name: "Paraguay", iso2: "PY", region: "latin-america" },
  "republic-of-peru": { name: "Peru", iso2: "PE", region: "latin-america" },
  "republic-of-poland": { name: "Poland", iso2: "PL", region: "europe" },
  "republic-of-rwanda": { name: "Rwanda", iso2: "RW", region: "middle-east-africa" },
  "republic-of-san-marino": { name: "San Marino", iso2: "SM", region: "europe" },
  "republic-of-senegal": { name: "Senegal", iso2: "SN", region: "middle-east-africa" },
  "republic-of-serbia": { name: "Serbia", iso2: "RS", region: "europe" },
  "republic-of-seychelles": { name: "Seychelles", iso2: "SC", region: "middle-east-africa" },
  "republic-of-sierra-leone": { name: "Sierra Leone", iso2: "SL", region: "middle-east-africa" },
  "republic-of-singapore": { name: "Singapore", iso2: "SG", region: "asia-pacific" },
  "republic-of-slovenia": { name: "Slovenia", iso2: "SI", region: "europe" },
  "republic-of-south-africa": { name: "South Africa", iso2: "ZA", region: "middle-east-africa" },
  "republic-of-south-sudan": { name: "South Sudan", iso2: "SS", region: "middle-east-africa" },
  "republic-of-suriname": { name: "Suriname", iso2: "SR", region: "latin-america" },
  "republic-of-tajikistan": { name: "Tajikistan", iso2: "TJ", region: "asia-pacific" },
  "republic-of-the-congo": { name: "Republic of the Congo", iso2: "CG", region: "middle-east-africa" },
  "republic-of-the-gambia": { name: "Gambia", iso2: "GM", region: "middle-east-africa" },
  "republic-of-the-maldives": { name: "Maldives", iso2: "MV", region: "asia-pacific" },
  "republic-of-the-marshall-islands": { name: "Marshall Islands", iso2: "MH", region: "asia-pacific" },
  "republic-of-the-philippines": { name: "Philippines", iso2: "PH", region: "asia-pacific" },
  "republic-of-the-sudan": { name: "Sudan", iso2: "SD", region: "middle-east-africa" },
  "republic-of-the-union-of-myanmar": { name: "Myanmar", iso2: "MM", region: "asia-pacific" },
  "republic-of-trinidad-and-tobago": { name: "Trinidad and Tobago", iso2: "TT", region: "latin-america" },
  "republic-of-trkiye": { name: "Türkiye", iso2: "TR", region: "middle-east-africa" },
  "republic-of-tunisia": { name: "Tunisia", iso2: "TN", region: "middle-east-africa" },
  "republic-of-turkey": { name: "Türkiye", iso2: "TR", region: "middle-east-africa" },
  "republic-of-uganda": { name: "Uganda", iso2: "UG", region: "middle-east-africa" },
  "republic-of-uzbekistan": { name: "Uzbekistan", iso2: "UZ", region: "asia-pacific" },
  "republic-of-vanuatu": { name: "Vanuatu", iso2: "VU", region: "asia-pacific" },
  "republic-of-yemen": { name: "Yemen", iso2: "YE", region: "middle-east-africa" },
  "republic-of-zambia": { name: "Zambia", iso2: "ZM", region: "middle-east-africa" },
  "republic-of-zimbabwe": { name: "Zimbabwe", iso2: "ZW", region: "middle-east-africa" },
  "republica-moldova": { name: "Moldova", iso2: "MD", region: "europe" },
  "republiek-suriname": { name: "Suriname", iso2: "SR", region: "latin-america" },
  "republik-indonesia": { name: "Indonesia", iso2: "ID", region: "asia-pacific" },
  "republik-singapura": { name: "Singapore", iso2: "SG", region: "asia-pacific" },
  "republika-hrvatska": { name: "Croatia", iso2: "HR", region: "europe" },
  "republika-slovenija": { name: "Slovenia", iso2: "SI", region: "europe" },
  "republika-srbija": { name: "Serbia", iso2: "RS", region: "europe" },
  "republika-yuburundi": { name: "Burundi", iso2: "BI", region: "middle-east-africa" },
  "republiken-finland": { name: "Finland", iso2: "FI", region: "europe" },
  "repubulika-yu-rwanda": { name: "Rwanda", iso2: "RW", region: "middle-east-africa" },
  "respublika-kazakhstan": { name: "Kazakhstan", iso2: "KZ", region: "asia-pacific" },
  "reunion": { name: "Réunion", iso2: "RE", region: "middle-east-africa" },
  "ribaberiki-kiribati": { name: "Kiribati", iso2: "KI", region: "asia-pacific" },
  "ripablik-blong-vanuatu": { name: "Vanuatu", iso2: "VU", region: "asia-pacific" },
  "ripublik-naoero": { name: "Nauru", iso2: "NR", region: "asia-pacific" },
  "romania": { name: "Romania", iso2: "RO", region: "europe" },
  "romnia": { name: "Romania", iso2: "RO", region: "europe" },
  "roumania": { name: "Romania", iso2: "RO", region: "europe" },
  "royaume-de-belgique": { name: "Belgium", iso2: "BE", region: "europe" },
  "rpublique-centrafricaine": { name: "Central African Republic", iso2: "CF", region: "middle-east-africa" },
  "rpublique-de-cte-divoire": { name: "Ivory Coast", iso2: "CI", region: "middle-east-africa" },
  "rpublique-de-djibouti": { name: "Djibouti", iso2: "DJ", region: "middle-east-africa" },
  "rpublique-de-guine": { name: "Guinea", iso2: "GN", region: "middle-east-africa" },
  "rpublique-de-guine-quatoriale": { name: "Equatorial Guinea", iso2: "GQ", region: "middle-east-africa" },
  "rpublique-de-madagascar": { name: "Madagascar", iso2: "MG", region: "middle-east-africa" },
  "rpublique-de-maurice": { name: "Mauritius", iso2: "MU", region: "middle-east-africa" },
  "rpublique-de-vanuatu": { name: "Vanuatu", iso2: "VU", region: "asia-pacific" },
  "rpublique-des-seychelles": { name: "Seychelles", iso2: "SC", region: "middle-east-africa" },
  "rpublique-dhati": { name: "Haiti", iso2: "HT", region: "latin-america" },
  "rpublique-du-bnin": { name: "Benin", iso2: "BJ", region: "middle-east-africa" },
  "rpublique-du-burundi": { name: "Burundi", iso2: "BI", region: "middle-east-africa" },
  "rpublique-du-cameroun": { name: "Cameroon", iso2: "CM", region: "middle-east-africa" },
  "rpublique-du-mali": { name: "Mali", iso2: "ML", region: "middle-east-africa" },
  "rpublique-du-rwanda": { name: "Rwanda", iso2: "RW", region: "middle-east-africa" },
  "rpublique-du-sngal": { name: "Senegal", iso2: "SN", region: "middle-east-africa" },
  "rpublique-du-tchad": { name: "Chad", iso2: "TD", region: "middle-east-africa" },
  "rpublique-franaise": { name: "France", iso2: "FR", region: "europe" },
  "rpublique-gabonaise": { name: "Gabon", iso2: "GA", region: "middle-east-africa" },
  "rpublique-togolaise": { name: "Togo", iso2: "TG", region: "middle-east-africa" },
  "rumania": { name: "Romania", iso2: "RO", region: "europe" },
  "runion": { name: "Réunion", iso2: "RE", region: "middle-east-africa" },
  "runion-island": { name: "Réunion", iso2: "RE", region: "middle-east-africa" },
  "russia": { name: "Russia", iso2: "RU", region: "europe" },
  "russian-federation": { name: "Russia", iso2: "RU", region: "europe" },
  "rwanda": { name: "Rwanda", iso2: "RW", region: "middle-east-africa" },
  "rzeczpospolita-polska": { name: "Poland", iso2: "PL", region: "europe" },
  "sahrawi-arab-democratic-republic": { name: "Western Sahara", iso2: "EH", region: "middle-east-africa" },
  "saint-barthlemy": { name: "Saint Barthélemy", iso2: "BL", region: "latin-america" },
  "saint-helena": { name: "Saint Helena, Ascension and Tristan da Cunha", iso2: "SH", region: "middle-east-africa" },
  "saint-helena-ascension-and-tristan-da-cunha": { name: "Saint Helena, Ascension and Tristan da Cunha", iso2: "SH", region: "middle-east-africa" },
  "saint-kitts-and-nevis": { name: "Saint Kitts and Nevis", iso2: "KN", region: "latin-america" },
  "saint-lucia": { name: "Saint Lucia", iso2: "LC", region: "latin-america" },
  "saint-martin": { name: "Saint Martin", iso2: "MF", region: "latin-america" },
  "saint-martin-french-part": { name: "Saint Martin", iso2: "MF", region: "latin-america" },
  "saint-pierre-and-miquelon": { name: "Saint Pierre and Miquelon", iso2: "PM", region: "north-america" },
  "saint-vincent-and-the-grenadines": { name: "Saint Vincent and the Grenadines", iso2: "VC", region: "latin-america" },
  "sakartvelo": { name: "Georgia", iso2: "GE", region: "middle-east-africa" },
  "salanat-umn": { name: "Oman", iso2: "OM", region: "middle-east-africa" },
  "samoa": { name: "Samoa", iso2: "WS", region: "asia-pacific" },
  "san-marino": { name: "San Marino", iso2: "SM", region: "europe" },
  "sankattan-siha-na-islas-marinas": { name: "Northern Mariana Islands", iso2: "MP", region: "asia-pacific" },
  "sao-tome-and-principe": { name: "São Tomé and Príncipe", iso2: "ST", region: "middle-east-africa" },
  "sarnam": { name: "Suriname", iso2: "SR", region: "latin-america" },
  "sathalanalat-paxathipatai-paxaxon-lao": { name: "Laos", iso2: "LA", region: "asia-pacific" },
  "saudi": { name: "Saudi Arabia", iso2: "SA", region: "middle-east-africa" },
  "saudi-arabia": { name: "Saudi Arabia", iso2: "SA", region: "middle-east-africa" },
  "schweiz": { name: "Switzerland", iso2: "CH", region: "europe" },
  "senegal": { name: "Senegal", iso2: "SN", region: "middle-east-africa" },
  "serbia": { name: "Serbia", iso2: "RS", region: "europe" },
  "seychelles": { name: "Seychelles", iso2: "SC", region: "middle-east-africa" },
  "shqipnia": { name: "Albania", iso2: "AL", region: "europe" },
  "shqipri": { name: "Albania", iso2: "AL", region: "europe" },
  "shqipria": { name: "Albania", iso2: "AL", region: "europe" },
  "sierra-leone": { name: "Sierra Leone", iso2: "SL", region: "middle-east-africa" },
  "singapore": { name: "Singapore", iso2: "SG", region: "asia-pacific" },
  "singapura": { name: "Singapore", iso2: "SG", region: "asia-pacific" },
  "sint-maarten": { name: "Sint Maarten", iso2: "SX", region: "latin-america" },
  "sint-maarten-dutch-part": { name: "Sint Maarten", iso2: "SX", region: "latin-america" },
  "slovak-republic": { name: "Slovakia", iso2: "SK", region: "europe" },
  "slovakia": { name: "Slovakia", iso2: "SK", region: "europe" },
  "slovenia": { name: "Slovenia", iso2: "SI", region: "europe" },
  "slovensk-republika": { name: "Slovakia", iso2: "SK", region: "europe" },
  "smoa-amelika": { name: "American Samoa", iso2: "AS", region: "asia-pacific" },
  "so-tom-and-prncipe": { name: "São Tomé and Príncipe", iso2: "ST", region: "middle-east-africa" },
  "socialist-republic-of-vietnam": { name: "Vietnam", iso2: "VN", region: "asia-pacific" },
  "solomon-islands": { name: "Solomon Islands", iso2: "SB", region: "asia-pacific" },
  "somalia": { name: "Somalia", iso2: "SO", region: "middle-east-africa" },
  "somers-isles": { name: "Bermuda", iso2: "BM", region: "north-america" },
  "south-africa": { name: "South Africa", iso2: "ZA", region: "middle-east-africa" },
  "south-georgia": { name: "South Georgia", iso2: "GS", region: "asia-pacific" },
  "south-georgia-and-the-south-sandwich-islands": { name: "South Georgia", iso2: "GS", region: "asia-pacific" },
  "south-korea": { name: "South Korea", iso2: "KR", region: "asia-pacific" },
  "south-sudan": { name: "South Sudan", iso2: "SS", region: "middle-east-africa" },
  "spain": { name: "Spain", iso2: "ES", region: "europe" },
  "sranangron": { name: "Suriname", iso2: "SR", region: "latin-america" },
  "srbija": { name: "Serbia", iso2: "RS", region: "europe" },
  "sri-lanka": { name: "Sri Lanka", iso2: "LK", region: "asia-pacific" },
  "st-barthelemy": { name: "Saint Barthélemy", iso2: "BL", region: "latin-america" },
  "st-helena-ascension-and-tristan-da-cunha": { name: "Saint Helena, Ascension and Tristan da Cunha", iso2: "SH", region: "middle-east-africa" },
  "state-of-eritrea": { name: "Eritrea", iso2: "ER", region: "middle-east-africa" },
  "state-of-israel": { name: "Israel", iso2: "IL", region: "middle-east-africa" },
  "state-of-kuwait": { name: "Kuwait", iso2: "KW", region: "middle-east-africa" },
  "state-of-libya": { name: "Libya", iso2: "LY", region: "middle-east-africa" },
  "state-of-palestine": { name: "Palestine", iso2: "PS", region: "middle-east-africa" },
  "state-of-qatar": { name: "Qatar", iso2: "QA", region: "middle-east-africa" },
  "stato-della-citt-del-vaticano": { name: "Vatican City", iso2: "VA", region: "europe" },
  "sudan": { name: "Sudan", iso2: "SD", region: "middle-east-africa" },
  "suid-afrika": { name: "South Africa", iso2: "ZA", region: "middle-east-africa" },
  "suisse": { name: "Switzerland", iso2: "CH", region: "europe" },
  "sultanate-of-oman": { name: "Oman", iso2: "OM", region: "middle-east-africa" },
  "suomen-tasavalta": { name: "Finland", iso2: "FI", region: "europe" },
  "suomi": { name: "Finland", iso2: "FI", region: "europe" },
  "suriname": { name: "Suriname", iso2: "SR", region: "latin-america" },
  "svalbard-and-jan-mayen": { name: "Svalbard and Jan Mayen", iso2: "SJ", region: "europe" },
  "svalbard-and-jan-mayen-islands": { name: "Svalbard and Jan Mayen", iso2: "SJ", region: "europe" },
  "svalbard-og-jan-mayen": { name: "Svalbard and Jan Mayen", iso2: "SJ", region: "europe" },
  "svizra": { name: "Switzerland", iso2: "CH", region: "europe" },
  "svizzera": { name: "Switzerland", iso2: "CH", region: "europe" },
  "swatini": { name: "Eswatini", iso2: "SZ", region: "middle-east-africa" },
  "swaziland": { name: "Eswatini", iso2: "SZ", region: "middle-east-africa" },
  "sweden": { name: "Sweden", iso2: "SE", region: "europe" },
  "swiss-confederation": { name: "Switzerland", iso2: "CH", region: "europe" },
  "switzerland": { name: "Switzerland", iso2: "CH", region: "europe" },
  "syria": { name: "Syria", iso2: "SY", region: "middle-east-africa" },
  "syrian-arab-republic": { name: "Syria", iso2: "SY", region: "middle-east-africa" },
  "taiwan": { name: "Taiwan", iso2: "TW", region: "asia-pacific" },
  "tajikistan": { name: "Tajikistan", iso2: "TJ", region: "asia-pacific" },
  "taneroft-tutrimt": { name: "Western Sahara", iso2: "EH", region: "middle-east-africa" },
  "tanzania": { name: "Tanzania", iso2: "TZ", region: "middle-east-africa" },
  "tanzania-united-republic-of": { name: "Tanzania", iso2: "TZ", region: "middle-east-africa" },
  "tchad": { name: "Chad", iso2: "TD", region: "middle-east-africa" },
  "teratri-of-norfk-ailen": { name: "Norfolk Island", iso2: "NF", region: "asia-pacific" },
  "territoire-des-les-wallis-et-futuna": { name: "Wallis and Futuna", iso2: "WF", region: "asia-pacific" },
  "territory-of-christmas-island": { name: "Christmas Island", iso2: "CX", region: "asia-pacific" },
  "territory-of-norfolk-island": { name: "Norfolk Island", iso2: "NF", region: "asia-pacific" },
  "territory-of-the-cocos-keeling-islands": { name: "Cocos (Keeling) Islands", iso2: "CC", region: "asia-pacific" },
  "territory-of-the-french-southern-and-antarctic-lands": { name: "French Southern and Antarctic Lands", iso2: "TF", region: "asia-pacific" },
  "territory-of-the-wallis-and-futuna-islands": { name: "Wallis and Futuna", iso2: "WF", region: "asia-pacific" },
  "tet-paragui": { name: "Paraguay", iso2: "PY", region: "latin-america" },
  "tet-volvia": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "thai": { name: "Thailand", iso2: "TH", region: "asia-pacific" },
  "thailand": { name: "Thailand", iso2: "TH", region: "asia-pacific" },
  "the-abode-of-peace": { name: "Brunei", iso2: "BN", region: "asia-pacific" },
  "the-bermudas": { name: "Bermuda", iso2: "BM", region: "north-america" },
  "the-former-yugoslav-republic-of-macedonia": { name: "North Macedonia", iso2: "MK", region: "europe" },
  "the-islands-of-bermuda": { name: "Bermuda", iso2: "BM", region: "north-america" },
  "the-netherlands": { name: "Netherlands", iso2: "NL", region: "europe" },
  "timor": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "timor-leste": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "timor-lorosae": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "timr-lorosae": { name: "Timor-Leste", iso2: "TL", region: "asia-pacific" },
  "tiwn": { name: "Taiwan", iso2: "TW", region: "asia-pacific" },
  "togo": { name: "Togo", iso2: "TG", region: "middle-east-africa" },
  "togolese": { name: "Togo", iso2: "TG", region: "middle-east-africa" },
  "togolese-republic": { name: "Togo", iso2: "TG", region: "middle-east-africa" },
  "toikiston": { name: "Tajikistan", iso2: "TJ", region: "asia-pacific" },
  "tokelau": { name: "Tokelau", iso2: "TK", region: "asia-pacific" },
  "tonga": { name: "Tonga", iso2: "TO", region: "asia-pacific" },
  "trinidad-and-tobago": { name: "Trinidad and Tobago", iso2: "TT", region: "latin-america" },
  "trkiye": { name: "Türkiye", iso2: "TR", region: "middle-east-africa" },
  "trkiye-cumhuriyeti": { name: "Türkiye", iso2: "TR", region: "middle-east-africa" },
  "tunisia": { name: "Tunisia", iso2: "TN", region: "middle-east-africa" },
  "tunisian-republic": { name: "Tunisia", iso2: "TN", region: "middle-east-africa" },
  "turkey": { name: "Türkiye", iso2: "TR", region: "middle-east-africa" },
  "turkiye": { name: "Türkiye", iso2: "TR", region: "middle-east-africa" },
  "turkmenistan": { name: "Turkmenistan", iso2: "TM", region: "asia-pacific" },
  "turks-and-caicos-islands": { name: "Turks and Caicos Islands", iso2: "TC", region: "latin-america" },
  "tuvalu": { name: "Tuvalu", iso2: "TV", region: "asia-pacific" },
  "uae": { name: "United Arab Emirates", iso2: "AE", region: "middle-east-africa" },
  "udzima-wa-komori": { name: "Comoros", iso2: "KM", region: "middle-east-africa" },
  "uganda": { name: "Uganda", iso2: "UG", region: "middle-east-africa" },
  "uk": { name: "United Kingdom", iso2: "GB", region: "europe" },
  "ukraine": { name: "Ukraine", iso2: "UA", region: "europe" },
  "ukrayina": { name: "Ukraine", iso2: "UA", region: "europe" },
  "umbuso-weswatini": { name: "Eswatini", iso2: "SZ", region: "middle-east-africa" },
  "umhuriyi-toikiston": { name: "Tajikistan", iso2: "TJ", region: "asia-pacific" },
  "union-des-comores": { name: "Comoros", iso2: "KM", region: "middle-east-africa" },
  "union-of-the-comoros": { name: "Comoros", iso2: "KM", region: "middle-east-africa" },
  "united-arab-emirates": { name: "United Arab Emirates", iso2: "AE", region: "middle-east-africa" },
  "united-kingdom": { name: "United Kingdom", iso2: "GB", region: "europe" },
  "united-kingdom-of-great-britain-and-northern-ireland": { name: "United Kingdom", iso2: "GB", region: "europe" },
  "united-mexican-states": { name: "Mexico", iso2: "MX", region: "latin-america" },
  "united-republic-of-tanzania": { name: "Tanzania", iso2: "TZ", region: "middle-east-africa" },
  "united-states": { name: "United States", iso2: "US", region: "north-america" },
  "united-states-minor-outlying-islands": { name: "United States Minor Outlying Islands", iso2: "UM", region: "latin-america" },
  "united-states-of-america": { name: "United States", iso2: "US", region: "north-america" },
  "united-states-virgin-islands": { name: "United States Virgin Islands", iso2: "VI", region: "latin-america" },
  "uruguay": { name: "Uruguay", iso2: "UY", region: "latin-america" },
  "usa": { name: "United States", iso2: "US", region: "north-america" },
  "uzbekistan": { name: "Uzbekistan", iso2: "UZ", region: "asia-pacific" },
  "vanuatu": { name: "Vanuatu", iso2: "VU", region: "asia-pacific" },
  "vatican": { name: "Vatican City", iso2: "VA", region: "europe" },
  "vatican-city": { name: "Vatican City", iso2: "VA", region: "europe" },
  "vatican-city-state": { name: "Vatican City", iso2: "VA", region: "europe" },
  "venezuela": { name: "Venezuela", iso2: "VE", region: "latin-america" },
  "venezuela-bolivarian-republic-of": { name: "Venezuela", iso2: "VE", region: "latin-america" },
  "viet-nam": { name: "Vietnam", iso2: "VN", region: "asia-pacific" },
  "vietnam": { name: "Vietnam", iso2: "VN", region: "asia-pacific" },
  "virgin-islands": { name: "British Virgin Islands", iso2: "VG", region: "latin-america" },
  "virgin-islands-british": { name: "British Virgin Islands", iso2: "VG", region: "latin-america" },
  "virgin-islands-of-the-united-states": { name: "United States Virgin Islands", iso2: "VI", region: "latin-america" },
  "virgin-islands-us": { name: "United States Virgin Islands", iso2: "VI", region: "latin-america" },
  "viti": { name: "Fiji", iso2: "FJ", region: "asia-pacific" },
  "waitu-kubuli": { name: "Dominica", iso2: "DM", region: "latin-america" },
  "wallis-and-futuna": { name: "Wallis and Futuna", iso2: "WF", region: "asia-pacific" },
  "western-sahara": { name: "Western Sahara", iso2: "EH", region: "middle-east-africa" },
  "weswatini": { name: "Eswatini", iso2: "SZ", region: "middle-east-africa" },
  "wuliwya": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "wuliwya-suyu": { name: "Bolivia", iso2: "BO", region: "latin-america" },
  "yemen": { name: "Yemen", iso2: "YE", region: "middle-east-africa" },
  "yemeni-republic": { name: "Yemen", iso2: "YE", region: "middle-east-africa" },
  "zambia": { name: "Zambia", iso2: "ZM", region: "middle-east-africa" },
  "zhnggu": { name: "China", iso2: "CN", region: "asia-pacific" },
  "zhnghu-mngu": { name: "Taiwan", iso2: "TW", region: "asia-pacific" },
  "zhnghu-rnmn-gnghgu": { name: "China", iso2: "CN", region: "asia-pacific" },
  "zhongguo": { name: "China", iso2: "CN", region: "asia-pacific" },
  "zhonghua": { name: "China", iso2: "CN", region: "asia-pacific" },
  "zimbabwe": { name: "Zimbabwe", iso2: "ZW", region: "middle-east-africa" },
};

// iso2 -> region, for callers that already hold the ISO code.
export const REGION_BY_ISO2: Record<string, FlashRegionKey> = {
  "AD": "europe",
  "AE": "middle-east-africa",
  "AF": "asia-pacific",
  "AG": "latin-america",
  "AI": "latin-america",
  "AL": "europe",
  "AM": "middle-east-africa",
  "AO": "middle-east-africa",
  "AQ": "asia-pacific",
  "AR": "latin-america",
  "AS": "asia-pacific",
  "AT": "europe",
  "AU": "asia-pacific",
  "AW": "latin-america",
  "AX": "europe",
  "AZ": "middle-east-africa",
  "BA": "europe",
  "BB": "latin-america",
  "BD": "asia-pacific",
  "BE": "europe",
  "BF": "middle-east-africa",
  "BG": "europe",
  "BH": "middle-east-africa",
  "BI": "middle-east-africa",
  "BJ": "middle-east-africa",
  "BL": "latin-america",
  "BM": "north-america",
  "BN": "asia-pacific",
  "BO": "latin-america",
  "BQ": "latin-america",
  "BR": "latin-america",
  "BS": "latin-america",
  "BT": "asia-pacific",
  "BV": "asia-pacific",
  "BW": "middle-east-africa",
  "BY": "europe",
  "BZ": "latin-america",
  "CA": "north-america",
  "CC": "asia-pacific",
  "CD": "middle-east-africa",
  "CF": "middle-east-africa",
  "CG": "middle-east-africa",
  "CH": "europe",
  "CI": "middle-east-africa",
  "CK": "asia-pacific",
  "CL": "latin-america",
  "CM": "middle-east-africa",
  "CN": "asia-pacific",
  "CO": "latin-america",
  "CR": "latin-america",
  "CU": "latin-america",
  "CV": "middle-east-africa",
  "CW": "latin-america",
  "CX": "asia-pacific",
  "CY": "europe",
  "CZ": "europe",
  "DE": "europe",
  "DJ": "middle-east-africa",
  "DK": "europe",
  "DM": "latin-america",
  "DO": "latin-america",
  "DZ": "middle-east-africa",
  "EC": "latin-america",
  "EE": "europe",
  "EG": "middle-east-africa",
  "EH": "middle-east-africa",
  "ER": "middle-east-africa",
  "ES": "europe",
  "ET": "middle-east-africa",
  "FI": "europe",
  "FJ": "asia-pacific",
  "FK": "latin-america",
  "FM": "asia-pacific",
  "FO": "europe",
  "FR": "europe",
  "GA": "middle-east-africa",
  "GB": "europe",
  "GD": "latin-america",
  "GE": "middle-east-africa",
  "GF": "latin-america",
  "GG": "europe",
  "GH": "middle-east-africa",
  "GI": "europe",
  "GL": "north-america",
  "GM": "middle-east-africa",
  "GN": "middle-east-africa",
  "GP": "latin-america",
  "GQ": "middle-east-africa",
  "GR": "europe",
  "GS": "asia-pacific",
  "GT": "latin-america",
  "GU": "asia-pacific",
  "GW": "middle-east-africa",
  "GY": "latin-america",
  "HK": "asia-pacific",
  "HM": "asia-pacific",
  "HN": "latin-america",
  "HR": "europe",
  "HT": "latin-america",
  "HU": "europe",
  "ID": "asia-pacific",
  "IE": "europe",
  "IL": "middle-east-africa",
  "IM": "europe",
  "IN": "asia-pacific",
  "IO": "middle-east-africa",
  "IQ": "middle-east-africa",
  "IR": "asia-pacific",
  "IS": "europe",
  "IT": "europe",
  "JE": "europe",
  "JM": "latin-america",
  "JO": "middle-east-africa",
  "JP": "asia-pacific",
  "KE": "middle-east-africa",
  "KG": "asia-pacific",
  "KH": "asia-pacific",
  "KI": "asia-pacific",
  "KM": "middle-east-africa",
  "KN": "latin-america",
  "KP": "asia-pacific",
  "KR": "asia-pacific",
  "KW": "middle-east-africa",
  "KY": "latin-america",
  "KZ": "asia-pacific",
  "LA": "asia-pacific",
  "LB": "middle-east-africa",
  "LC": "latin-america",
  "LI": "europe",
  "LK": "asia-pacific",
  "LR": "middle-east-africa",
  "LS": "middle-east-africa",
  "LT": "europe",
  "LU": "europe",
  "LV": "europe",
  "LY": "middle-east-africa",
  "MA": "middle-east-africa",
  "MC": "europe",
  "MD": "europe",
  "ME": "europe",
  "MF": "latin-america",
  "MG": "middle-east-africa",
  "MH": "asia-pacific",
  "MK": "europe",
  "ML": "middle-east-africa",
  "MM": "asia-pacific",
  "MN": "asia-pacific",
  "MO": "asia-pacific",
  "MP": "asia-pacific",
  "MQ": "latin-america",
  "MR": "middle-east-africa",
  "MS": "latin-america",
  "MT": "europe",
  "MU": "middle-east-africa",
  "MV": "asia-pacific",
  "MW": "middle-east-africa",
  "MX": "latin-america",
  "MY": "asia-pacific",
  "MZ": "middle-east-africa",
  "NA": "middle-east-africa",
  "NC": "asia-pacific",
  "NE": "middle-east-africa",
  "NF": "asia-pacific",
  "NG": "middle-east-africa",
  "NI": "latin-america",
  "NL": "europe",
  "NO": "europe",
  "NP": "asia-pacific",
  "NR": "asia-pacific",
  "NU": "asia-pacific",
  "NZ": "asia-pacific",
  "OM": "middle-east-africa",
  "PA": "latin-america",
  "PE": "latin-america",
  "PF": "asia-pacific",
  "PG": "asia-pacific",
  "PH": "asia-pacific",
  "PK": "asia-pacific",
  "PL": "europe",
  "PM": "north-america",
  "PN": "asia-pacific",
  "PR": "latin-america",
  "PS": "middle-east-africa",
  "PT": "europe",
  "PW": "asia-pacific",
  "PY": "latin-america",
  "QA": "middle-east-africa",
  "RE": "middle-east-africa",
  "RO": "europe",
  "RS": "europe",
  "RU": "europe",
  "RW": "middle-east-africa",
  "SA": "middle-east-africa",
  "SB": "asia-pacific",
  "SC": "middle-east-africa",
  "SD": "middle-east-africa",
  "SE": "europe",
  "SG": "asia-pacific",
  "SH": "middle-east-africa",
  "SI": "europe",
  "SJ": "europe",
  "SK": "europe",
  "SL": "middle-east-africa",
  "SM": "europe",
  "SN": "middle-east-africa",
  "SO": "middle-east-africa",
  "SR": "latin-america",
  "SS": "middle-east-africa",
  "ST": "middle-east-africa",
  "SV": "latin-america",
  "SX": "latin-america",
  "SY": "middle-east-africa",
  "SZ": "middle-east-africa",
  "TC": "latin-america",
  "TD": "middle-east-africa",
  "TF": "asia-pacific",
  "TG": "middle-east-africa",
  "TH": "asia-pacific",
  "TJ": "asia-pacific",
  "TK": "asia-pacific",
  "TL": "asia-pacific",
  "TM": "asia-pacific",
  "TN": "middle-east-africa",
  "TO": "asia-pacific",
  "TR": "middle-east-africa",
  "TT": "latin-america",
  "TV": "asia-pacific",
  "TW": "asia-pacific",
  "TZ": "middle-east-africa",
  "UA": "europe",
  "UG": "middle-east-africa",
  "UM": "latin-america",
  "US": "north-america",
  "UY": "latin-america",
  "UZ": "asia-pacific",
  "VA": "europe",
  "VC": "latin-america",
  "VE": "latin-america",
  "VG": "latin-america",
  "VI": "latin-america",
  "VN": "asia-pacific",
  "VU": "asia-pacific",
  "WF": "asia-pacific",
  "WS": "asia-pacific",
  "XK": "europe",
  "YE": "middle-east-africa",
  "YT": "middle-east-africa",
  "ZA": "middle-east-africa",
  "ZM": "middle-east-africa",
  "ZW": "middle-east-africa",
};
